services:
  - type: web
    name: meghanvaya-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m backend.seed"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: USE_SQLITE_FALLBACK
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "11520"
